// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmdbvhEMol6CzngXNSRONTyyZcdetlH1Y',
    appId: '1:331982447534:web:b3076fd920aba61ebb9e3f',
    messagingSenderId: '331982447534',
    projectId: 'loginsignupauth-594c1',
    authDomain: 'loginsignupauth-594c1.firebaseapp.com',
    storageBucket: 'loginsignupauth-594c1.appspot.com',
    measurementId: 'G-Q613KDM52F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArGZjDM7L116ARAYW5B4vOHVHgXxwZZTY',
    appId: '1:331982447534:android:d9ed52ff386514cbbb9e3f',
    messagingSenderId: '331982447534',
    projectId: 'loginsignupauth-594c1',
    storageBucket: 'loginsignupauth-594c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgippX5M2utsT-_0nhJRtBR3yuXWzqigw',
    appId: '1:331982447534:ios:a6c6887796695cd8bb9e3f',
    messagingSenderId: '331982447534',
    projectId: 'loginsignupauth-594c1',
    storageBucket: 'loginsignupauth-594c1.appspot.com',
    iosBundleId: 'com.example.loginSignupWithAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgippX5M2utsT-_0nhJRtBR3yuXWzqigw',
    appId: '1:331982447534:ios:a6c6887796695cd8bb9e3f',
    messagingSenderId: '331982447534',
    projectId: 'loginsignupauth-594c1',
    storageBucket: 'loginsignupauth-594c1.appspot.com',
    iosBundleId: 'com.example.loginSignupWithAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmdbvhEMol6CzngXNSRONTyyZcdetlH1Y',
    appId: '1:331982447534:web:65027973479856a3bb9e3f',
    messagingSenderId: '331982447534',
    projectId: 'loginsignupauth-594c1',
    authDomain: 'loginsignupauth-594c1.firebaseapp.com',
    storageBucket: 'loginsignupauth-594c1.appspot.com',
    measurementId: 'G-S5J52V9HP7',
  );
}
